site_name: Mis Apuntes 2

theme:
  name: 'material'
  icon:
    repo: 'fontawesome/brands/github'

theme:
  name: 'material'
  font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'

theme:
  palette:
      - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

      - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar

extra_css:
  - css/styles.css

extra_templates:
  - docs/index.html

nav:
    - Inicio: index.md
    - Apuntes: Microprocesadores_Marp.md

plugins:
    - search
    - print-site:
        add_to_navigation: false
        print_page_title: 'Print Site'
        print_page_basename: 'print_page'
        add_print_site_banner: false
        # Table of contents
        add_table_of_contents: true
        toc_title: 'Table of Contents'
        toc_depth: 6
        # Content-related
        add_full_urls: false
        enumerate_headings: true
        enumerate_figures: true
        add_cover_page: true
        cover_page_template: ""
        path_to_pdf: ""
        include_css: true
        enabled: true
    - pdf-export:
        combined: true
    - page-to-pdf:
        opcio: valor
    - with-pdf
theme:
    name: 'material'
    features:
      - navigation.sections
      - navigation.top
      - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
    custom_fences:
      - name: mermaid
      class: mermaidformat: !!python/name:pymdownx.superfences.fence_code_format
   - pymdownx.snippets
  


 
 

