site_name: Mis Apuntes 2

theme:
  name: 'material'
  icon:
    repo: 'fontawesome/brands/github'

theme:
  name: 'material'
  font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'

theme:
  palette:
      - scheme: default
      toggle:
          icon: material/brightness-7 
          name: Canvia a mode oscur

      - scheme: slate
      toggle:
          icon: material/brightness-4
          name: Canvia a mode clar

extra_css:
  - css/styles.css

extra_templates:
  - docs/index.html

nav:
    - Inicio: index.md
    - Apuntes: Microprocesadores_Marp.md



